// Recipe row = [name, emoji, diet(v=vegan,t=veg,n=non), meals, kcal, protein, carbs, fat, time, ingredients, steps, gradient]
export const R=[
['Masala Oats','🥣','v','Breakfast',320,11,52,8,'10 min',['½ cup rolled oats','1 cup water','¼ onion, diced','1 tomato, chopped','Handful peas','½ tsp turmeric, cumin, salt','Coriander to finish'],['Sauté onion, tomato and spices in a little oil for 2 min.','Add peas, oats and water.','Simmer 5 min, stirring, until creamy.','Top with coriander.'],'#ffb36b,#ff6f91'],
['Paneer Bhurji Wrap','🌯','t','Breakfast',410,24,35,19,'15 min',['100 g paneer, crumbled','1 whole-wheat roti','½ onion, ½ tomato','Green chilli, turmeric, salt','1 tsp oil'],['Heat oil, cook onion and chilli until soft.','Add tomato and turmeric, cook 2 min.','Stir in paneer for 3 min.','Spoon into the roti and roll.'],'#ffd86b,#f08a4b'],
['Egg Spinach Scramble','🍳','n','Breakfast',340,24,6,24,'8 min',['3 eggs','1 cup baby spinach','1 tsp olive oil','Salt, pepper','1 slice whole-grain toast'],['Whisk eggs with salt and pepper.','Wilt spinach in oil 1 min.','Pour in eggs, fold gently until just set.','Serve with toast.'],'#ffe27a,#7fd48a'],
['Berry Chia Pudding','🫐','v','Breakfast,Snack',280,8,30,14,'5 min + overnight',['3 tbsp chia seeds','¾ cup almond milk','1 tsp maple syrup','½ cup mixed berries'],['Mix chia, milk and syrup.','Chill at least 4 hours.','Top with berries.'],'#9b8cff,#ff7aa8'],
['Chickpea Quinoa Bowl','🥗','v','Lunch',480,19,64,16,'20 min',['½ cup quinoa','1 cup chickpeas','Cucumber, cherry tomatoes','Lemon, olive oil','Cumin, salt','Parsley'],['Cook quinoa in 1 cup water, 12 min.','Toss chickpeas with cumin.','Combine with chopped veg.','Dress with lemon, oil, salt.'],'#8ee07a,#2de2c0'],
['Grilled Chicken Rice Bowl','🍗','n','Lunch,Dinner',560,45,58,14,'25 min',['150 g chicken breast','¾ cup cooked brown rice','Broccoli florets','1 tsp olive oil','Garlic, paprika, salt, lemon'],['Season chicken with garlic, paprika, salt.','Grill 5–6 min per side until 74°C inside.','Steam broccoli 4 min.','Slice chicken, serve over rice with lemon.'],'#ffb36b,#ff6f6f'],
['Paneer Tikka Salad','🧀','t','Lunch',430,26,18,28,'20 min',['120 g paneer cubes','Yogurt, tikka masala','Bell pepper, onion','Mixed greens','Lemon'],['Marinate paneer and veg in yogurt and masala 15 min.','Pan-sear or grill until charred.','Serve on greens with lemon.'],'#ff9d6b,#c1ff7a'],
['Dal Tadka & Brown Rice','🍛','v','Lunch,Dinner',520,22,84,9,'30 min',['½ cup toor dal','¾ cup cooked brown rice','1 tomato','Garlic, cumin, mustard seeds','Turmeric, chilli, salt','1 tsp oil'],['Pressure-cook dal with turmeric and salt until soft.','Heat oil, pop cumin and mustard seeds.','Add garlic, chilli, tomato; cook 3 min.','Pour tadka over dal and serve with rice.'],'#ffd24d,#ff8f4d'],
['Garlic Butter Salmon','🐟','n','Dinner',520,40,8,35,'18 min',['150 g salmon fillet','1 tbsp butter','2 garlic cloves','Asparagus','Lemon, salt, pepper'],['Season salmon; sear skin-side down 4 min.','Flip, add butter and garlic, cook 3 min.','Roast or pan-cook asparagus.','Finish with lemon.'],'#ff8fa3,#6bd0ff'],
['Tofu Veggie Stir-fry','🥦','v','Dinner',380,22,30,18,'20 min',['150 g firm tofu','Broccoli, carrot, bell pepper','1 tbsp soy sauce','Ginger, garlic','1 tsp sesame oil'],['Press and cube the tofu; sear until golden.','Stir-fry veg with ginger and garlic 4 min.','Add tofu, soy sauce and sesame oil.','Toss 1 min and serve.'],'#7ae0a1,#ffc46b'],
['Greek Yogurt Parfait','🍨','t','Snack,Breakfast',220,16,28,5,'3 min',['¾ cup Greek yogurt','2 tbsp granola','½ banana, sliced','Honey drizzle'],['Layer yogurt, banana and granola in a glass.','Finish with honey.'],'#ffc9de,#ffe08a'],
['Roasted Chana','🥜','v','Snack',180,10,26,4,'25 min',['1 cup boiled chickpeas','½ tsp oil','Chaat masala, chilli, salt'],['Pat chickpeas dry.','Toss with oil and spices.','Roast at 200°C for 20 min, shaking once.'],'#e8b86b,#a86b4b'],
['Tuna Avocado Toast','🥑','n','Snack,Breakfast',300,24,24,13,'7 min',['1 slice whole-grain toast','½ avocado','½ can tuna in water','Lemon, pepper, chilli flakes'],['Mash avocado with lemon and pepper.','Spread on toast.','Top with flaked tuna and chilli.'],'#a8e063,#56ab2f']];